site_name: BearCar Documentation
site_url: https://UCAEngineeringPhysics.github.io/BearCar/
repo_url: https://github.com/UCAEngineeringPhysics/BearCar/
nav:
  - Home: index.md
    # - Quick Start: quick_start.md
  - Wiring Guide: wiring.md
  - Components List: components.md
  - Assembly Guide: assembly.md
  - Gamepad Keymap: gamepad.md
    # - Software Installation and Test Guide: software.md
    # - Data Collection Guide: collect_data.md
    # - Autopilot Training Guide: train.md
    # - Autopilot Deployment Guide: deploy.md
  # - API Reference: api.md

theme:
  name: readthedocs
