site_name: BearCar Documentation
site_url: https://UCAEngineeringPhysics.github.io/BearCar/
repo_url: https://github.com/UCAEngineeringPhysics/BearCar/
nav:
  - Home: index.md
    # - Quick Start: quick_start.md
  - Wiring Guide: wiring.md
  - Components List: components.md
  - Assembly Guide: assembly.md
  - Gamepad Keymap: gamepad.md
  - Mode Indicator: led.md
  - Pilot Configurations: configs.md
    # - Software Installation and Test Guide: software.md
  - Data Collection Guide: data.md
  - Autopilot Training Guide: learn.md
  - Autopilot Deployment Guide: autopilot.md
  # - API Reference: api.md

theme:
  name: readthedocs
